baseurl = "/"
languageCode = "en-us"
title = "Data Documentation for datatxt.org"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:slug/"
    note = "/note/:slug/"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Datasets"
    url = "/dataset/"
    weight = 2

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; datatxt.org 2019"
